name: Run Bash Script on Arch Docker Container and Create Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      # Run Arch Docker container and execute the script
      - name: Run Bash script on Arch Docker container
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace archlinux bash /workspace/script.sh

      # Collect all .pkg.tar.zst files and compress them
      - name: Find and compress .pkg.tar.zst files
        run: |
          # Find all .pkg.tar.zst files and create a tarball
          tar -czf packages.tar.gz $(find . -name "*.pkg.tar.zst")

      # Create a GitHub release
      - name: Create GitHub release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: packages.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Upload the release assets
      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: packages.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
